# Generated by Django 4.2.11 on 2026-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wifi', '0002_wifiaccesslog_ip_address_wifiaccesslog_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
